// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from '@/providers/authProvider';
import { Providers } from '@/components/Providers';
import NavbarWrapper from "@/components/NavbarWrapper";
import TokenRefresher from '@/components/TokenRefresher';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
        <Providers >
        <TokenRefresher />
        <NavbarWrapper />
          {children}
        </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}