import {
    FaHome,
    FaUsers,
    FaExchangeAlt,
    FaCreditCard,
    FaBrain,
    FaChartBar,
    FaCog,
    FaBell,
    FaSearch,
    FaUser,
    FaSignOutAlt,
    FaUserTie,
    FaIndustry,
    FaBoxOpen,
    FaHistory,
    FaQuestionCircle,
    FaComments,
  } from "react-icons/fa";
  
  export const iconComponents = {
    FaHome,
    FaUsers,
    FaExchangeAlt,
    FaBrain,
    FaCreditCard,
    FaChartBar,
    FaCog,
    FaBell,
    FaSearch,
    FaUser,
    FaSignOutAlt,
    FaUserTie,
    FaIndustry,
    FaBoxOpen,
    FaHistory,
    FaQuestionCircle,
    FaComments,
  };